### ISSUE TITLE
Visio 2013 Support with Powershell Modules

### ISSUE THREAD

**Issue by ianclegg** [saveenr/VisioAutomation#1]
Hi,

Im trying to use the poweshell module to create  a directed graph in Visio 2013. I can run:
New-VisioApplication
New-VisioDocument
Import-VisioModel <xml> -Verbose

I can see some output stating 
VERBOSE: Root element name =orgchart
VERBOSE: Loading as an Org Chart
VERBOSE: Walking XML
VERBOSE: Loading shape: 0 Akuma
VERBOSE: Loading shape: 1 Ryu 0
VERBOSE: Loading shape: 2 Ken 0
VERBOSE: Loading shape: 3 Chun-Li 2
VERBOSE: Finished Walking XML
VERBOSE: Finished Creating OrgChart model
but nothing is rendered in Visio?

Am I doing something wrong?

**Comment by saveenr** [comment]
Thanks for reporting. I will try to look at this today.

**Comment by ianclegg** [comment]
Wow! Thanks... let me know if you need a hand with testing
I only have Visio 2013 installed

**Comment by ianclegg** [comment]
@saveen I was missing the pipe to Out-Visio... Once thats add it works fine!
Thanks
