### ISSUE TITLE
VisioAutomation and automatic-graph-layout 

### ISSUE THREAD

**Issue by gabrieldelaparra** [saveenr/VisioAutomation#6]
Hi there! I saw that you were working with automatic-graph-layout. Have you been able to draw a diagram in Visio from it?

**Comment by saveenr** [comment]
Absolutely :-) 

https://github.com/saveenr/VisioAutomation/blob/master/VisioAutomation_2010/TestVisioAutomation/Models/DirectedGraph_Tests.cs

See this set of unit tests - it shows how to build a directed graph "model" and then render it using automatic-graph-layout.
